### ISSUE TITLE
Opt-In version - Voting module doesn't work

### ISSUE THREAD

**Issue by cryptoBeliever** [NemProject/NanoWallet#609]
Voting module doesn't work in latest version (it worked in 2.4.7 without opt-in).
Steps: 
1. Go to Services -> Voting -> See pools

Result:
![image](https://user-images.githubusercontent.com/17684281/101215943-f2125900-367e-11eb-9565-2114396180c4.png)

In console:
```
main.js:96539 TypeError: rxjs_1.Observable.fromPromise is not a function
    at Function.PollIndex.fromAddress
```

**Comment by jabo38** [comment]
I tested the option version of the voting center and it was definitely messed up like the screen shot above.  But I also tested an older 2.4.7 version of the desktop wallet and was able to vote fine. 

As per making a poll, it was strange in that I couldn't see the field where I was supposed to enter the date.

**Comment by QuantumMechanics** [comment]
Opt-in version is using an old version of the voting module... I would like to fix but blocked by #610

**Comment by QuantumMechanics** [comment]
Fixed in 2.4.8
